//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public int IdOrderProduct { get; set; }
        public int Count { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPoint { get; set; }
        public string NameClient { get; set; }
        public int Code { get; set; }
        public int IdStatus { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
    }
}
