//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int ProductArticleNumber { get; set; }
        public int IdProductName { get; set; }
        public int IdUnit { get; set; }
        public decimal ProductCost { get; set; }
        public int MaxSales { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductSupplier { get; set; }
        public int IdProductCategory { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string Photo { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        public virtual NameManufacturer NameManufacturer { get; set; }
        public virtual NameProduct NameProduct { get; set; }
        public virtual NameSupplier NameSupplier { get; set; }
        public virtual NameUnit NameUnit { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
